/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wlopera' at '10/3/16 10:11 PM' with Gradle 2.14.1
 *
 * @author wlopera, @date 10/3/16 10:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
